### ISSUE TITLE
(next.js) 선호도 설정에서 음식 사진 호버 시 출현하는 음식 이름 위치 조정

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#133]
## Description

![image](https://github.com/jagaldol/chat-foodie/assets/84557643/da2aec09-8af3-4a92-825e-d8348e5d16f1)

현재 음식 이름이 위와 같이 안내되고 있습니다.

마우스 위치에 출현하던지 차라리 오른쪽에 나오는 게 낫지 않을까요? 아래 이미지랑 겹쳐서 개선에 대해 논의가 필요할 것 같습니다.

또한 출현하는 레전드 스타일도 논의를 했으면 좋겠습니다.

**Comment by sm136599** [comment]
레전드 스타일 하나 제안 하겠습니다.

이미지에 마우스 올릴 시, 이미지는 약간 투명하게 되고 음식 이름이 사진 중앙에 나타나게 하는 건 어떤가요?

이해를 돕기 위해 이미지를 첨부합니다.
<img width="275" alt="image" src="https://github.com/jagaldol/chat-foodie/assets/74234978/65964e24-63ee-4d5f-af33-f7361f271079">

**Comment by jagaldol** [comment]
> 레전드 스타일 하나 제안 하겠습니다.
> 
> 이미지에 마우스 올릴 시, 이미지는 약간 투명하게 되고 음식 이름이 사진 중앙에 나타나게 하는 건 어떤가요?

괜찮은데요? 그런데 음식 사진이 너무 색깔이 강하거나 현란하거나 어둡거나 하면 글씨가 잘 안보이지 않을까요?

음식 사진 좀더 흐리게 하는게 낫지않나 생각이 드네요 근데 발상은 너무 좋고 맘에 들어요

투명도는 실험적으로 여러값 넣어보고 모든 사진들을 고려했을때 제일 괜찮은걸로 하죠

그냥 검정 이미지일때로 글씨 어느정도 보이는지 한번 테스트해보면 좋을거 같습니다
