### ISSUE TITLE
회원가입시 서버오류

### ISSUE THREAD

**Issue by sm136599** [jagaldol/chat-foodie#45]
## Description

로그인 아이디, 비밀번호, 이메일 등 만족하게 보냈지만 500 서버 오류가 생깁니다.

## Tasks

POST(join) 으로 다음과 같이 요청하였을 때 오류가 생김
- request body
```json
{
  "loginId": "sm136599",
  "password": "asdf123@",
  "passwordCheck": "string",
  "name": "string",
  "gender": true,
  "birth": "2401-68-82",
  "email": "sm136599@gmail.com"
}
```
- response body
```json
{
  "status": 500,
  "response": null,
  "errorMessage": "회원가입 중에 오류가 발생했습니다. 다시 시도해주세요."
}
```
- response headers
```
 cache-control: no-cache,no-store,max-age=0,must-revalidate 
 connection: close 
 content-type: application/json;charset=UTF-8 
 date: Tue,01 Aug 2023 06:02:35 GMT 
 expires: 0 
 pragma: no-cache 
 transfer-encoding: chunked 
 vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers 
 x-content-type-options: nosniff 
 x-frame-options: SAMEORIGIN 
 x-xss-protection: 0 
```

## 의심가는 상황
- 생일 입력 시 월, 일의 범위가 비정상적이면 500 서버에러가 나는 것 같습니다.

**Comment by sm136599** [comment]
윤년 포함 정규표현식이 있는 블로그

https://hoony-devblog.tistory.com/15

/^(?=\d)(?:(?:31(?!.(?:0?[2469]|11))|(?:30|29)(?!.0?2)|29(?=.0?2.(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00)))(?:\x20|$))|(?:2[0-8]|1\d|0?[1-9]))([-.\/])(?:1[012]|0?[1-9])\1(?:1[6-9]|[2-9]\d)?\d\d(?:(?=\x20\d)\x20|$))?(((0?[1-9]|1[012])(:[0-5]\d){0,2}(\x20[AP]M))|([01]\d|2[0-3])(:[0-5]\d){1,2})?$/

**Comment by jagaldol** [comment]
![image](https://github.com/jagaldol/chat-foodie/assets/84557643/e2dd0188-d931-4103-854f-06e0b3a61dfd)

비밀번호 이상 확인
