### ISSUE TITLE
(chatbot) 배포용 서버 선택

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#83]
## Description

나중에 챗봇 서버를 배포하기 위해 서버 선택이 필요한데 가격이 적당한 최소 성능의 서버를 빌려야합니다.

먼저 AWS의 경우 GPU는 제일 싼게 시간당 `0.5166 USD` 으로 환율 1315원으로 계산 시 시간당 680원, 한달 50만원입니다.

그러면 눈을 돌려 CPU로 가면 16gb 메모리의 경우 시간당 `0.122 USD` -> 시간당 160원, 한달 12만원입니다.

16gb가 모자랄 수 있는데 이러면 32gb로 가야합니다. 이 경우 시간당 `0.244 USD` -> 시간당 320원 ,한달 24만원입니다.

해법으로 AWS 스케쥴러가 있습니다. 정해진 시간에만 켜두게 해서 밤에는 동작안하게 하면 1/3은 아낄 수 있을 겁니다.

---

AWS가 전체적으로 비싸 싼 클라우드 서비스를 탐색해야합니다. 먼저 Vast.ai를 찾았습니다. 챗봇 서버에 양자화 옵션이 있어 GPU 메모리 12GB로 충분히 구동이 가능합니다. Vast.ai에서 가장 싼걸로 하면 시간당 `0.096 USD` 쯤 합니다. 시간당 126원, 한달 10만원 가량입니다.

양자화가 필요하지만 GPU로 구동하는 만큼 속도도 빠를겁니다. 근데 한달 10만원도 역시 부담스럽긴 합니다.

여기는 스케쥴링 그런 건 없는 거 같고 한번에 크래딧 구매하면 할인이 있는 거 같긴 합니다.

---

아니면 GPU가 아닌 CPU 서버도 괜찮으니 메모리 32기가짜리 엄청 싼 클라우드 서비스를 찾아도 좋습니다. 현실적인 가격의 서버를 찾아야합니다.

<br/>

<br/>

스프링과 리액트를 실행할 서버의 경우 간단하게 aws 무료 프리티어에서 구동 가능하므로 신경 안써도 됩니다.

## References

- [AWS 인스턴스 종류](https://ap-northeast-2.console.aws.amazon.com/ec2/home?region=ap-northeast-2#InstanceTypes:)
- [AWS 스케쥴러](https://aws.amazon.com/ko/solutions/implementations/instance-scheduler-on-aws/)
- [Vast.ai GPU 서버](https://cloud.vast.ai/create/)

**Comment by sm136599** [comment]
colab으로 돌렸을 시 사용량을 기준으로 google cloud service에서 가격 견적을 내 봤습니다.
* 시스템 메모리 사용량: 약 4GB
* GPU 메모리 사용량: 약 12GB 이상
* 디스크 사용량: 47GB

이를 바탕으로 다음과 같이 견적을 짜 보았습니다.
* 시스템 메모리: 7GB
* GPU: Tesla T4
* GPU 메모리: 16GB
* 디스크: 64GB
위와 같이 서버를 사용할 시 한달 약 18만원의 비용이 발생합니다.
https://cloud.google.com/products/calculator/#id=0b9411fc-7dd4-479c-9d48-077d8c46cfde

**Comment by jagaldol** [comment]
일단은 연구실 서버 대여를 통해 해결하였고 나중에 필요할 떈 Vast.ai같은걸로 잠깐 키는걸로 하며 이슈를 닫습니다.
